version: 1.0.{build}
configuration: Release 

before_build:
  - nuget restore
    
build:
  project: cscpci.sln
  verbosity: minimal

test:
  assemblies:
    - 'bin\*\*.test.dll'

test_script:
    - nunit-console <assembly> --result=TestResult.xml;format=AppVeyor
